version: "3.9"

services:
  # Backend FastAPI
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./secure_cloud.db
    volumes:
      - ./backend:/app
      - backend-data:/app
    command: python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - securecloud

  # OAuth2 Proxy
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-proxy
    restart: unless-stopped
    environment:
      OAUTH2_PROXY_PROVIDER: github
      OAUTH2_PROXY_CLIENT_ID: Ov23lieaz4pXFExWxPqL
      OAUTH2_PROXY_CLIENT_SECRET: a108cd44d56b995bf676cf7aebea3ec9e003458e
      OAUTH2_PROXY_COOKIE_SECRET: pBe4DAOLaUUjABJeiaeml5dO3WsuGvMiAzp5LqSA9k4=

      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_HTTP_ADDRESS: :4180
      # Proxy vers nginx qui g√®re frontend + backend
      OAUTH2_PROXY_UPSTREAMS: http://nginx:80

      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
      OAUTH2_PROXY_PASS_USER_HEADERS: "true"

      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_COOKIE_SAMESITE: "lax"
      OAUTH2_PROXY_COOKIE_EXPIRE: "4h"
      OAUTH2_PROXY_COOKIE_REFRESH: "0"
      
      OAUTH2_PROXY_REDIRECT_URL: "http://localhost:4180/oauth2/callback"
    ports:
      - "4180:4180"
    networks:
      - securecloud
    depends_on:
      - nginx

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - securecloud
    depends_on:
      - backend

networks:
  securecloud:
    driver: bridge

volumes:
  backend-data:
