version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "4180:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - oauth2-proxy

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-proxy
    restart: unless-stopped
    ports:
      - "4181:4180"
    environment:
      OAUTH2_PROXY_PROVIDER: github
      OAUTH2_PROXY_CLIENT_ID: Ov23livji01V79ZnVum5
      OAUTH2_PROXY_CLIENT_SECRET: aecea85c4f8eed312272ff4043fb16b357edf289
      OAUTH2_PROXY_COOKIE_SECRET: pBe4DAOLaUUjABJeiaeml5dO3WsuGvMiAzp5LqSA9k4=

      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_HTTP_ADDRESS: :4180
      OAUTH2_PROXY_REDIRECT_URL: "http://localhost:4180/oauth2/callback"
      # Upstream factice car utilis√© uniquement pour auth_request
      OAUTH2_PROXY_UPSTREAMS: "http://host.docker.internal:5173"

      OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"

      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_COOKIE_SAMESITE: "lax"
      OAUTH2_PROXY_COOKIE_EXPIRE: "4h"
      OAUTH2_PROXY_COOKIE_REFRESH: "0"
    
    extra_hosts:
      - "host.docker.internal:host-gateway"